[project]
name="ccao"
#version=0.01
cppversion="c++11"
debug=false
cpp=true# g++ or gcc
apps=[
    #每一个app应该是相互独立的 如果需要 请你导出为star并添加到depends里面
    #"app1",
    "public",
    "classes",
    "tools"
]
depends=[
    #"1$version"
    "toml"
]