[project]
name="ccao"
#version=0.01
cppversion="c++11"
debug=true
cpp=true# g++ or gcc
cflag=""#额外参数 默认为空
ccache=true
apps=[
    #每一个app应该是相互独立的 如果需要 请你导出为star并添加到depends里面
    #"app1",
    "public",
    "classes",
    "tools"
]
depends=[
    "toml$0"
]