[project]
name="ccao"
#version=0.01
cppversion="c++11"
debug=true
cflag=""#额外参数 默认为空
ccache=true
compiler="g++"
version="0"
apps=[
    #每一个app应该是相互独立的 如果需要 请你导出为star并添加到depends里面
    #"app1",
    "base",
    "public",
    "utils",
]
depends=[
    #"toml$0"
]