#include <string>
#include <Cproject.h>
#include <Cconfig.h>
#include <Star.h>
bool debug;
std::string root;
std::string cflag;
std::string extra_cflag;
std::string include_path;
std::string libray_path;
std::string home;
bool isProject;
bool cpp;
bool isStar;
Cconfig *config;
Cproject *project;
Star *star;
std::string help_text;
std::string exe_file_path;